
title = {"code":"代码", "symbol": "ID", "name": "名称", "industry": "所属行业", "date":"日期", "open": "开盘价", "settlement":"昨日收盘价", "high":"最高价", "close": "收盘价", "low":"最低价","volume":"成交量", "amount": "成交金额", "price_change": "价格变动","p_change":"涨跌幅", 
    "ma5": "5日均价", "ma10": "10日均价", "ma20": "20日均价", "v_ma5": "5日均量", "v_ma10": "10日均量", "v_ma20": "20日均量", "turnover": "换手率",
    "ts_code": "TS代码",
"trade_date": "交易日期",
"buy_sm_vol": "小单买入量（手）",
"buy_sm_amount": "小单买入金额（万元）",
"sell_sm_vol": "小单卖出量（手）",
"sell_sm_amount": "小单卖出金额（万元）",
"buy_md_vol": "中单买入量（手）",
"buy_md_amount": "中单买入金额（万元）",
"sell_md_vol": "中单卖出量（手）",
"sell_md_amount": "中单卖出金额（万元）",
"buy_lg_vol": "大单买入量（手）",
"buy_lg_amount": "大单买入金额（万元）",
"sell_lg_vol": "大单卖出量（手）",
"sell_lg_amount": "大单卖出金额（万元）",
"buy_elg_vol": "特大单买入量（手）",
"buy_elg_amount": "特大单买入金额（万元）",
"sell_elg_vol": "特大单卖出量（手）",
"sell_elg_amount": "特大单卖出金额（万元）",
"net_mf_vol": "净流入量（手）",
"net_mf_amount": "净流入额（万元）",
"trade_date": "交易日期", "pre_close": "昨收价",
"change": "涨跌额","pct_chg": "涨跌幅","vol": "成交量 （手）",
'colse0': "收盘价0",
'turnover_rate':'换手率',
'purchase_sum':'主力买入总量',
'purchase_sum_per': '主力控盘比例',
'float_share': '流通股本'
}

longhu_title = {'SCode': '代码','SName': '名称','ClosePrice': '收盘价','Chgradio': '涨跌幅','Dchratio': '换手率','JmMoney': '龙虎榜净买额(万)','Turnover': '市场总成交额(万)',
    'Ntransac': '','Ctypedes': '上榜原因','Oldid': '','Smoney': '龙虎榜卖出额(万)','BMoney': '龙虎榜买入额(万)',
    'ZeMoney': '龙虎榜成交额(万)','Tdate': '上榜日','JmRate': '净买额占总成交比','ZeRate': '成交额占总成交比',
    'Ltsz': '流通市值(亿)','Rchange1dc': '上榜后1日','Rchange1do': '','Rchange2dc': '上榜后2日','Rchange2do':'','Rchange3dc':'',
    'Rchange3do': '','Rchange5dc':'上榜后5日','Rchange5do':'','Rchange10dc':'上榜后10日','Rchange10do':'','Rchange15dc':'','Rchange15do':'',
    'Rchange20dc':'','Rchange20do':'','Rchange30dc':'','Rchange30do':'','Rchange1m':'','Rchange3m':'','Rchange6m':'','Rchange1y':'','SumCount':'','JGBSumCount':'',
    'JGSSumCount':'','JGBMoney':'','JGSMoney':'','JGJMMoney':'','DP':'解读'}